# Generated by Django 4.1.7 on 2023-02-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutes',
            name='bus_date',
            field=models.DateField(null=True, verbose_name='rute date'),
        ),
    ]
